#@TYPE: Machine
#@NAME: NETFIELD IO-LINK EDGE GATEWAY Rev2
#@DESCRIPTION: netFIELD (IP67) module with netRAPID 90, UCM8.Mini Quad, 2GB RAM, no onboard Wifi/BT, 16GB eMMC, no further options
#@PARTNUMBERS: 1915.000R2
#@MAINTAINER: Hilscher Gesellschaft fuer Systemautomation mbH
#@TEMPLATECONF: meta-hilscher-netfield-imx8/conf/samples

#-------------------------------------------------------------------------------
include conf/machine/include/imx8.inc
SOC_FAMILY .= ":netfield-iolink-edge-gw-revx"

#-------------------------------------------------------------------------------
PRECONFIGURED_SYSTEM_CONNECTIONS ?= "eth0 cifx0"

# Enable service by default since platform provides cloud LEDs
SYSTEMD_MACHINE_STATE_SERVICE_AUTO_ENABLE ?= "enable"

SWU_FILES += "${IMX_BOOT_FILE};boot1.bin"
SWU_FILE_ATTRIBUTES += "boot1.bin;path=\"/dev/mmcblk1\";offset=\"${IMX_BOOT_SEEK}K\";name=\"boot.bin\";version;install-if-different=true"

# password required to interrupt auto boot process and enter console
UBOOT_PW = "Xdb8DqTw"

OEM_BRANDING_IMAGES = "hilscher-netfield-image-oem-netfield hilscher-netfield-image-oem-sensoredge"
