#@TYPE: Machine
#@NAME: NIOT-E-NFL90-Q2N16-N
#@DESCRIPTION: netFLEX with netRAPID 90, UCM8.Mini Quad, 2GB RAM, no onboard Wifi/BT, 16GB eMMC, no further options
#@PARTNUMBERS: 1320.400r1
#@MAINTAINER: Hilscher Gesellschaft fuer Systemautomation mbH
#@TEMPLATECONF: meta-hilscher-netfield-imx8/conf/samples

#-------------------------------------------------------------------------------
include conf/machine/include/imx8.inc
SOC_FAMILY .= ":niot-e-nfl90-q2n16-n-revx"

#-------------------------------------------------------------------------------
MACHINE_FEATURES += "pci wifi 3g"

MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS:append = " kernel-module-netanalyzer libnetana netanalyzer-firmware netanalyzer-bsl"
MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS:append = " uionetx"

# To be able to use Intel WiFi / BT card
MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS:append = " linux-firmware-iwlwifi-misc linux-firmware-ibt"
KERNEL_FEATURES:append:pn-linux-imx = " features/iwlwifi/iwlwifi.scc"
KERNEL_FEATURES:append:pn-linux-fslc-imx = " features/iwlwifi/iwlwifi.scc"

BAD_RECOMMENDATIONS:pn-hilscher-rescue-images += " \
    kernel-module-netanalyzer libnetana netanalyzer-firmware netanalyzer-bsl \
    kernel-module-uio-netx \
    kernel-5.15* \
"

OEM_BRANDING_IMAGES = "hilscher-netfield-image-oem-netfield"

