# We have a conf and classes directory, add to BBPATH
BBPATH := "${BBPATH}:${LAYERDIR}"

# We have a recipes directory, add to BBFILES
BBFILES := "${BBFILES} ${LAYERDIR}/recipes-*/*/*.bb \
	    ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "hilscher-netfield-imx8"
BBFILE_PATTERN_hilscher-netfield-imx8 := "^${LAYERDIR}/"
BBFILE_PRIORITY_hilscher-netfield-imx8 = "100"

LAYERSERIES_COMPAT_hilscher-netfield-imx8 = "dunfell"
LAYERDEPENDS_hilscher-netfield-imx8 = " \
	core yocto hilscher-netfield hilscher-netfield-oem compulab-bsp-imx8mm freescale-layer gplv2 \
	security tpm-layer openembedded-layer multimedia-layer networking-layer perl-layer meta-python \
	webserver swupdate \
"

KEYS_DIR := "${LAYERDIR}/keys"

# Generic machines used for OEM base images
BBMULTICONFIG += " \
	niot-e-nfl90-q2n16-n-rev1 \
	netfield-iolink-edge-gw-rev2 \
"

# Vendor machines used for OEM overlay images
BBMULTICONFIG += " \
	hilscher-niot-e-nfl90-q2n16-n-rev1 \
	hilscher-netfield-iolink-edge-gw-rev2 \
"

do_image[mcdepends] += "mc:hilscher-niot-e-nfl90-q2n16-n-rev1:niot-e-nfl90-q2n16-n-rev1:netfield-image-oem:do_image_complete"
do_image[mcdepends] += "mc:hilscher-netfield-iolink-edge-gw-rev2:netfield-iolink-edge-gw-rev2:netfield-image-oem:do_image_complete"

BSP_DEPLOYSCRIPT_DIR = "${LAYERDIR}/scripts/deploy"
